TRUNCATE TABLE redis_name RESTART IDENTITY;
TRUNCATE TABLE geocode RESTART IDENTITY;
TRUNCATE TABLE rule RESTART IDENTITY CASCADE;
TRUNCATE TABLE occupation RESTART IDENTITY CASCADE;
TRUNCATE TABLE industry RESTART IDENTITY CASCADE;