codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"
  status:
    project: off
    patch: off
    # project:
    #   default:
    #     target: auto
    #     threshold: 1%
    # patch:
    #   default:
    #     target: 50%
    #     threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no