image:
  file: docker/.gitpod.Dockerfile
tasks:
  - command: make start
ports:
  - name: graphql
    description: api
    port: 10000
    onOpen: ignore
    visibility: public
  - name: rule
    description: automates transactions
    port: 10001
    onOpen: ignore
  - name: request-create
    description: creates transaction requests
    port: 10002
    onOpen: ignore
  - name: request-approve
    description: approves transaction requests
    port: 10003
    onOpen: ignore
  - name: balance-by-account
    description: queries a balance by account
    port: 10004
    onOpen: ignore
  - name: requests-by-account
    description: queries transaction requests by account
    port: 10006
    onOpen: ignore
  - name: request-by-id
    description: queries a transaction request by id
    port: 10005
    onOpen: ignore
  - name: transactions-by-account
    description: queries transactions by account
    port: 10008
    onOpen: ignore
  - name: transaction-by-id
    description: queries a transaction by id
    port: 10007
    onOpen: ignore
  - name: client
    description: web client
    port: 10009
    onOpen: ignore
  - name: postgres
    description: db
    port: 5432
    onOpen: ignore
vscode:
  extensions:
    - rangav.vscode-thunder-client@2.5.3
    - hashicorp.terraform
    - svelte.svelte-vscode
    - shd101wyy.markdown-preview-enhanced
    - GraphQL.vscode-graphql
    - wmaurer.change-case
    - dbaeumer.vscode-eslint
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
    - rust-lang.rust-analyzer
