[workspace]
resolver = "2"

members = [
	"crates/cognitoidp",
	"crates/httpclient",
	"crates/pg",
	"crates/service",
	"crates/shutdown",
	"crates/types",
	"services/graphql",
	"services/request-approve",
	"services/request-by-id",
	"services/request-create",
	"services/rule",
	"tests",
]

[workspace.package]
rust-version = "1.75"
