TRUNCATE TABLE approval RESTART IDENTITY CASCADE;
TRUNCATE TABLE transaction_item RESTART IDENTITY CASCADE;
TRUNCATE TABLE transaction RESTART IDENTITY CASCADE;
TRUNCATE TABLE rule_instance RESTART IDENTITY CASCADE;
TRUNCATE TABLE account RESTART IDENTITY CASCADE;
TRUNCATE TABLE account_profile RESTART IDENTITY CASCADE;
TRUNCATE TABLE account_owner RESTART IDENTITY CASCADE;
TRUNCATE TABLE account_balance RESTART IDENTITY CASCADE;