version: 2.1
executors:
  react-executor:
    docker:
      - image: mxfactorial/circleci:v1
    working_directory: ~/repo/react
jobs:
  react-build-test-dev:
    executor: react-executor
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Detect changed subdirectory files since last successful build
          command: |
            . ../.circleci/scripts/detect-project.sh react
      - restore_cache:
          paths:
            - node_modules
          key: v021-dependencies-{{ checksum "package.json" }}
      - run: make test ENV=dev
      - run: make e2e ENV=dev
      - run:
          name: Build web client for acceptance testing
          command: make build ENV=dev
      - save_cache:
          paths:
            - node_modules
          key: v021-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - build
            - makefile
  react-deploy-dev:
    executor: react-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Exit if build directory NOT present after early client build termination
          #from build/ attached above
          command: |
            if [[ ! -f build/index.html ]]; then
              circleci step halt
            fi
      - run:
          name: Deploy to S3 and terminate cache
          #from build/ attached above
          command: make deploy ENV=dev
  react-build-test-prod:
    executor: react-executor
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Detect changed subdirectory files since last successful build
          command: |
            . ../.circleci/scripts/detect-project.sh react
      - restore_cache:
          paths:
            - node_modules
          key: v021-dependencies-{{ checksum "package.json" }}
      - run: make test ENV=prod
      - run: make e2e ENV=prod
      - run:
          name: Build web client for prod environment
          command: make build ENV=prod
      - save_cache:
          paths:
            - node_modules
          key: v021-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - build
            - makefile
  react-deploy-prod:
    executor: react-executor
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: .
      - run:
          name: Exit if build directory NOT present after early client build termination
          #from build/ attached above
          command: |
            if [[ ! -f build/index.html ]]; then
              circleci step halt
            fi
      - run:
          name: Deploy to S3 and terminate cache
          #from build/ attached above
          command: make deploy ENV=prod
  services-dev:
    docker:
      - image: mxfactorial/circleci:v1
    working_directory: ~/repo/services
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Detect changed subdirectory files since last successful build
          command: |
            . ../.circleci/scripts/detect-project.sh services
      - run:
          name: Set Go Environment Variables
          command: |
            echo 'export GOPATH=$HOME/go' >> $BASH_ENV
            echo 'export GOBIN=$GOPATH/bin' >> $BASH_ENV
            echo 'export PATH=/usr/local/go/bin:$PATH' >> $BASH_ENV
            source /home/circleci/.bashrc
      - run:
          name: Install dependencies, archive, then deploy
          command: make deploy ENV=dev
      - run:
          name: Test dev endpoints
          working_directory: ~/repo/services/graphql-faas
          command: make test ENV=dev
  services-prod:
    docker:
      - image: mxfactorial/circleci:v1
    working_directory: ~/repo/services
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Detect changed subdirectory files since last successful build
          command: |
            . ../.circleci/scripts/detect-project.sh services
      - run:
          name: Set Go Environment Variables
          command: |
            echo 'export GOPATH=$HOME/go' >> $BASH_ENV
            echo 'export GOBIN=$GOPATH/bin' >> $BASH_ENV
            echo 'export PATH=/usr/local/go/bin:$PATH' >> $BASH_ENV
            source /home/circleci/.bashrc
      - run:
          name: Install dependencies, archive, then deploy
          command: make deploy ENV=prod
workflows:
  version: 2.1
  react-build-test-deploy-dev:
    jobs:
      - react-build-test-dev:
          filters:
            tags:
              only: /.*accept.*/
      - react-deploy-dev:
          requires:
            - react-build-test-dev
          # filters:
          #   branches:
          #     ignore: /.*/
          # deploy accept tags only
          # tags:
          #   only:
          #     - /.*accept.*/
  react-build-test-deploy-prod:
    jobs:
      - react-build-test-prod:
          filters:
            branches:
              only:
                - master
      - react-deploy-prod:
          requires:
            - react-build-test-prod
          filters:
            branches:
              only:
                - master
  services:
    jobs:
      - services-dev:
          filters:
            branches:
              only:
                - /^(master.+|(?!master).*)$/
      - services-prod:
          filters:
            branches:
              only:
                - master
