[package]
name = "sqls"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-query = { version = "0.30.7", default-features = false, features = [
	"backend-postgres",
	"derive",
	"sea-query-derive",
] }
types = { path = "../types" }
