// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/systemaccounting/mxfactorial/pkg/aws/apigwma (interfaces: IAWSAPIGWMA)

// Package mock_apigwma is a generated GoMock package.
package mock_apigwma

import (
	reflect "reflect"

	apigatewaymanagementapi "github.com/aws/aws-sdk-go/service/apigatewaymanagementapi"
	gomock "github.com/golang/mock/gomock"
)

// MockIAWSAPIGWMA is a mock of IAWSAPIGWMA interface.
type MockIAWSAPIGWMA struct {
	ctrl     *gomock.Controller
	recorder *MockIAWSAPIGWMAMockRecorder
}

// MockIAWSAPIGWMAMockRecorder is the mock recorder for MockIAWSAPIGWMA.
type MockIAWSAPIGWMAMockRecorder struct {
	mock *MockIAWSAPIGWMA
}

// NewMockIAWSAPIGWMA creates a new mock instance.
func NewMockIAWSAPIGWMA(ctrl *gomock.Controller) *MockIAWSAPIGWMA {
	mock := &MockIAWSAPIGWMA{ctrl: ctrl}
	mock.recorder = &MockIAWSAPIGWMAMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAWSAPIGWMA) EXPECT() *MockIAWSAPIGWMAMockRecorder {
	return m.recorder
}

// CreatePostToConnectionInput mocks base method.
func (m *MockIAWSAPIGWMA) CreatePostToConnectionInput(arg0 *string, arg1 []byte) *apigatewaymanagementapi.PostToConnectionInput {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePostToConnectionInput", arg0, arg1)
	ret0, _ := ret[0].(*apigatewaymanagementapi.PostToConnectionInput)
	return ret0
}

// CreatePostToConnectionInput indicates an expected call of CreatePostToConnectionInput.
func (mr *MockIAWSAPIGWMAMockRecorder) CreatePostToConnectionInput(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePostToConnectionInput", reflect.TypeOf((*MockIAWSAPIGWMA)(nil).CreatePostToConnectionInput), arg0, arg1)
}

// Marshal mocks base method.
func (m *MockIAWSAPIGWMA) Marshal(arg0 interface{}) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Marshal", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Marshal indicates an expected call of Marshal.
func (mr *MockIAWSAPIGWMAMockRecorder) Marshal(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Marshal", reflect.TypeOf((*MockIAWSAPIGWMA)(nil).Marshal), arg0)
}

// PostToConnection mocks base method.
func (m *MockIAWSAPIGWMA) PostToConnection(arg0 *apigatewaymanagementapi.PostToConnectionInput) (*apigatewaymanagementapi.PostToConnectionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostToConnection", arg0)
	ret0, _ := ret[0].(*apigatewaymanagementapi.PostToConnectionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostToConnection indicates an expected call of PostToConnection.
func (mr *MockIAWSAPIGWMAMockRecorder) PostToConnection(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostToConnection", reflect.TypeOf((*MockIAWSAPIGWMA)(nil).PostToConnection), arg0)
}
