// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/systemaccounting/mxfactorial/services/gopkg/lambdapg (interfaces: Connector,SQLDB,PGUnmarshaler)

// Package mock_lambdapg is a generated GoMock package.
package mock_lambdapg

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgconn "github.com/jackc/pgconn"
	pgx "github.com/jackc/pgx/v4"
	decimal "github.com/shopspring/decimal"
	lambdapg "github.com/systemaccounting/mxfactorial/services/gopkg/lambdapg"
	types "github.com/systemaccounting/mxfactorial/services/gopkg/types"
)

// MockConnector is a mock of Connector interface.
type MockConnector struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorMockRecorder
}

// MockConnectorMockRecorder is the mock recorder for MockConnector.
type MockConnectorMockRecorder struct {
	mock *MockConnector
}

// NewMockConnector creates a new mock instance.
func NewMockConnector(ctrl *gomock.Controller) *MockConnector {
	mock := &MockConnector{ctrl: ctrl}
	mock.recorder = &MockConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnector) EXPECT() *MockConnectorMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockConnector) Connect(arg0 context.Context, arg1 string) (lambdapg.SQLDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", arg0, arg1)
	ret0, _ := ret[0].(lambdapg.SQLDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Connect indicates an expected call of Connect.
func (mr *MockConnectorMockRecorder) Connect(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockConnector)(nil).Connect), arg0, arg1)
}

// MockSQLDB is a mock of SQLDB interface.
type MockSQLDB struct {
	ctrl     *gomock.Controller
	recorder *MockSQLDBMockRecorder
}

// MockSQLDBMockRecorder is the mock recorder for MockSQLDB.
type MockSQLDBMockRecorder struct {
	mock *MockSQLDB
}

// NewMockSQLDB creates a new mock instance.
func NewMockSQLDB(ctrl *gomock.Controller) *MockSQLDB {
	mock := &MockSQLDB{ctrl: ctrl}
	mock.recorder = &MockSQLDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLDB) EXPECT() *MockSQLDBMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockSQLDB) Begin(arg0 context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", arg0)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockSQLDBMockRecorder) Begin(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockSQLDB)(nil).Begin), arg0)
}

// Close mocks base method.
func (m *MockSQLDB) Close(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSQLDBMockRecorder) Close(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSQLDB)(nil).Close), arg0)
}

// Exec mocks base method.
func (m *MockSQLDB) Exec(arg0 context.Context, arg1 string, arg2 ...interface{}) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockSQLDBMockRecorder) Exec(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockSQLDB)(nil).Exec), varargs...)
}

// IsClosed mocks base method.
func (m *MockSQLDB) IsClosed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsClosed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsClosed indicates an expected call of IsClosed.
func (mr *MockSQLDBMockRecorder) IsClosed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsClosed", reflect.TypeOf((*MockSQLDB)(nil).IsClosed))
}

// Query mocks base method.
func (m *MockSQLDB) Query(arg0 context.Context, arg1 string, arg2 ...interface{}) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockSQLDBMockRecorder) Query(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockSQLDB)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockSQLDB) QueryRow(arg0 context.Context, arg1 string, arg2 ...interface{}) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockSQLDBMockRecorder) QueryRow(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockSQLDB)(nil).QueryRow), varargs...)
}

// MockPGUnmarshaler is a mock of PGUnmarshaler interface.
type MockPGUnmarshaler struct {
	ctrl     *gomock.Controller
	recorder *MockPGUnmarshalerMockRecorder
}

// MockPGUnmarshalerMockRecorder is the mock recorder for MockPGUnmarshaler.
type MockPGUnmarshalerMockRecorder struct {
	mock *MockPGUnmarshaler
}

// NewMockPGUnmarshaler creates a new mock instance.
func NewMockPGUnmarshaler(ctrl *gomock.Controller) *MockPGUnmarshaler {
	mock := &MockPGUnmarshaler{ctrl: ctrl}
	mock.recorder = &MockPGUnmarshalerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPGUnmarshaler) EXPECT() *MockPGUnmarshalerMockRecorder {
	return m.recorder
}

// UnmarshalAccountBalance mocks base method.
func (m *MockPGUnmarshaler) UnmarshalAccountBalance(arg0 pgx.Row) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalAccountBalance", arg0)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalAccountBalance indicates an expected call of UnmarshalAccountBalance.
func (mr *MockPGUnmarshalerMockRecorder) UnmarshalAccountBalance(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalAccountBalance", reflect.TypeOf((*MockPGUnmarshaler)(nil).UnmarshalAccountBalance), arg0)
}

// UnmarshalAccountBalances mocks base method.
func (m *MockPGUnmarshaler) UnmarshalAccountBalances(arg0 pgx.Rows) ([]*types.AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalAccountBalances", arg0)
	ret0, _ := ret[0].([]*types.AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalAccountBalances indicates an expected call of UnmarshalAccountBalances.
func (mr *MockPGUnmarshalerMockRecorder) UnmarshalAccountBalances(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalAccountBalances", reflect.TypeOf((*MockPGUnmarshaler)(nil).UnmarshalAccountBalances), arg0)
}

// UnmarshalAccountProfileIDs mocks base method.
func (m *MockPGUnmarshaler) UnmarshalAccountProfileIDs(arg0 pgx.Rows) ([]*types.AccountProfileID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalAccountProfileIDs", arg0)
	ret0, _ := ret[0].([]*types.AccountProfileID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalAccountProfileIDs indicates an expected call of UnmarshalAccountProfileIDs.
func (mr *MockPGUnmarshalerMockRecorder) UnmarshalAccountProfileIDs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalAccountProfileIDs", reflect.TypeOf((*MockPGUnmarshaler)(nil).UnmarshalAccountProfileIDs), arg0)
}

// UnmarshalApprovals mocks base method.
func (m *MockPGUnmarshaler) UnmarshalApprovals(arg0 pgx.Rows) ([]*types.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalApprovals", arg0)
	ret0, _ := ret[0].([]*types.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalApprovals indicates an expected call of UnmarshalApprovals.
func (mr *MockPGUnmarshalerMockRecorder) UnmarshalApprovals(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalApprovals", reflect.TypeOf((*MockPGUnmarshaler)(nil).UnmarshalApprovals), arg0)
}

// UnmarshalID mocks base method.
func (m *MockPGUnmarshaler) UnmarshalID(arg0 pgx.Row) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalID", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalID indicates an expected call of UnmarshalID.
func (mr *MockPGUnmarshalerMockRecorder) UnmarshalID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalID", reflect.TypeOf((*MockPGUnmarshaler)(nil).UnmarshalID), arg0)
}

// UnmarshalIDs mocks base method.
func (m *MockPGUnmarshaler) UnmarshalIDs(arg0 pgx.Rows) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalIDs", arg0)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalIDs indicates an expected call of UnmarshalIDs.
func (mr *MockPGUnmarshalerMockRecorder) UnmarshalIDs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalIDs", reflect.TypeOf((*MockPGUnmarshaler)(nil).UnmarshalIDs), arg0)
}

// UnmarshalTrItems mocks base method.
func (m *MockPGUnmarshaler) UnmarshalTrItems(arg0 pgx.Rows) ([]*types.TransactionItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalTrItems", arg0)
	ret0, _ := ret[0].([]*types.TransactionItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalTrItems indicates an expected call of UnmarshalTrItems.
func (mr *MockPGUnmarshalerMockRecorder) UnmarshalTrItems(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalTrItems", reflect.TypeOf((*MockPGUnmarshaler)(nil).UnmarshalTrItems), arg0)
}

// UnmarshalTransaction mocks base method.
func (m *MockPGUnmarshaler) UnmarshalTransaction(arg0 pgx.Row) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalTransaction", arg0)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalTransaction indicates an expected call of UnmarshalTransaction.
func (mr *MockPGUnmarshalerMockRecorder) UnmarshalTransaction(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalTransaction", reflect.TypeOf((*MockPGUnmarshaler)(nil).UnmarshalTransaction), arg0)
}

// UnmarshalTransactionNotifications mocks base method.
func (m *MockPGUnmarshaler) UnmarshalTransactionNotifications(arg0 pgx.Rows) ([]*types.TransactionNotification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalTransactionNotifications", arg0)
	ret0, _ := ret[0].([]*types.TransactionNotification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalTransactionNotifications indicates an expected call of UnmarshalTransactionNotifications.
func (mr *MockPGUnmarshalerMockRecorder) UnmarshalTransactionNotifications(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalTransactionNotifications", reflect.TypeOf((*MockPGUnmarshaler)(nil).UnmarshalTransactionNotifications), arg0)
}

// UnmarshalTransactions mocks base method.
func (m *MockPGUnmarshaler) UnmarshalTransactions(arg0 pgx.Rows) ([]*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalTransactions", arg0)
	ret0, _ := ret[0].([]*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalTransactions indicates an expected call of UnmarshalTransactions.
func (mr *MockPGUnmarshalerMockRecorder) UnmarshalTransactions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalTransactions", reflect.TypeOf((*MockPGUnmarshaler)(nil).UnmarshalTransactions), arg0)
}

// UnmarshalWebsocket mocks base method.
func (m *MockPGUnmarshaler) UnmarshalWebsocket(arg0 pgx.Row) (*types.Websocket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalWebsocket", arg0)
	ret0, _ := ret[0].(*types.Websocket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalWebsocket indicates an expected call of UnmarshalWebsocket.
func (mr *MockPGUnmarshalerMockRecorder) UnmarshalWebsocket(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalWebsocket", reflect.TypeOf((*MockPGUnmarshaler)(nil).UnmarshalWebsocket), arg0)
}

// UnmarshalWebsockets mocks base method.
func (m *MockPGUnmarshaler) UnmarshalWebsockets(arg0 pgx.Rows) ([]*types.Websocket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalWebsockets", arg0)
	ret0, _ := ret[0].([]*types.Websocket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalWebsockets indicates an expected call of UnmarshalWebsockets.
func (mr *MockPGUnmarshalerMockRecorder) UnmarshalWebsockets(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalWebsockets", reflect.TypeOf((*MockPGUnmarshaler)(nil).UnmarshalWebsockets), arg0)
}
