package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"

	"github.com/systemaccounting/mxfactorial/services/graphql/graph/model"
)

// CreateRequest is the resolver for the createRequest field.
func (r *mutationResolver) CreateRequest(ctx context.Context, transactionItems []*model.TransactionItemInput, authAccount string) (*model.Transaction, error) {
	panic(fmt.Errorf("not implemented: CreateRequest - createRequest"))
}

// ApproveRequest is the resolver for the approveRequest field.
func (r *mutationResolver) ApproveRequest(ctx context.Context, transactionID string, accountName string, accountRole string, authAccount string) (*model.Transaction, error) {
	panic(fmt.Errorf("not implemented: ApproveRequest - approveRequest"))
}

// Rules is the resolver for the rules field.
func (r *queryResolver) Rules(ctx context.Context, transactionItems []*model.TransactionItemInput) (*model.Transaction, error) {
	panic(fmt.Errorf("not implemented: Rules - rules"))
}

// RequestByID is the resolver for the requestByID field.
func (r *queryResolver) RequestByID(ctx context.Context, transactionID string, authAccount string) (*model.Transaction, error) {
	panic(fmt.Errorf("not implemented: RequestByID - requestByID"))
}

// RequestsByAccount is the resolver for the requestsByAccount field.
func (r *queryResolver) RequestsByAccount(ctx context.Context, accountName string, authAccount string) ([]*model.Transaction, error) {
	panic(fmt.Errorf("not implemented: RequestsByAccount - requestsByAccount"))
}

// TransactionByID is the resolver for the transactionByID field.
func (r *queryResolver) TransactionByID(ctx context.Context, transactionID string, authAccount string) (*model.Transaction, error) {
	panic(fmt.Errorf("not implemented: TransactionByID - transactionByID"))
}

// TransactionsByAccount is the resolver for the transactionsByAccount field.
func (r *queryResolver) TransactionsByAccount(ctx context.Context, accountName string, authAccount string) ([]*model.Transaction, error) {
	panic(fmt.Errorf("not implemented: TransactionsByAccount - transactionsByAccount"))
}

// Balance is the resolver for the balance field.
func (r *queryResolver) Balance(ctx context.Context, accountName string, authAccount string) (*string, error) {
	panic(fmt.Errorf("not implemented: Balance - balance"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
