#@ load("@ytt:data", "data")
#@ app = "graphql"
#@ app_port = data.values.GRAPHQL_PORT
#@ image_version = "latest"
#@ image = "{}/{}/{}/{}:{}".format(data.values.GITHUB_REGISTRY, data.values.GITHUB_ORG, data.values.GITHUB_REPO_NAME, app, image_version)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ app + "-deployment"
  labels:
    app: #@ app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #@ app
  template:
    metadata:
      labels:
        app: #@ app
    spec:
      containers:
        - name: #@ app
          image: #@ image
          ports:
            - containerPort: #@ app_port
          env:
            - name: RULE_URL
              value: #@ "http://rule:" + "{}".format(data.values.RULE_PORT)
            - name: REQUEST_CREATE_URL
              value: #@ "http://request-create:" + "{}".format(data.values.REQUEST_CREATE_PORT)
            - name: REQUEST_APPROVE_URL
              value: #@ "http://request-approve:" + "{}".format(data.values.REQUEST_APPROVE_PORT)
            - name: REQUEST_BY_ID_URL
              value: #@ "http://request-by-id:" + "{}".format(data.values.REQUEST_BY_ID_PORT)
            - name: REQUESTS_BY_ACCOUNT_URL
              value: #@ "http://requests-by-account:" + "{}".format(data.values.REQUESTS_BY_ACCOUNT_PORT)
            - name: TRANSACTIONS_BY_ACCOUNT_URL
              value: #@ "http://transactions-by-account:" + "{}".format(data.values.TRANSACTIONS_BY_ACCOUNT_PORT)
            - name: TRANSACTION_BY_ID_URL
              value: #@ "http://transaction-by-id:" + "{}".format(data.values.TRANSACTION_BY_ID_PORT)
            - name: BALANCE_BY_ACCOUNT_URL
              value: #@ "http://balance-by-account:" + "{}".format(data.values.BALANCE_BY_ACCOUNT_PORT)
            - name: READINESS_CHECK_PATH
              value: #@ data.values.READINESS_CHECK_PATH
            - name: RUST_LOG
              value: "info"
            - name: GRAPHQL_PORT
              value: #@ "{}".format(app_port)
          livenessProbe:
            httpGet:
              path: #@ data.values.READINESS_CHECK_PATH
              port: #@ app_port
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: #@ data.values.READINESS_CHECK_PATH
              port: #@ app_port
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: #@ app
spec:
  selector:
    app: #@ app
  ports:
    - protocol: TCP
      port: #@ app_port
      targetPort: #@ app_port
  type: ClusterIP