#@ load("@ytt:data", "data")
#@ app = "postgres"
#@ app_port = data.values.PGPORT
#@ image_version = "latest"
#@ image = "{}/{}/{}/{}:{}".format(data.values.GITHUB_REGISTRY, data.values.GITHUB_ORG, data.values.GITHUB_REPO_NAME, app, image_version)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ app + "-deployment"
  labels:
    app: #@ app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #@ app
  template:
    metadata:
      labels:
        app: #@ app
    spec:
      containers:
        - name: #@ app
          image: #@ image
          ports:
            - containerPort: #@ app_port
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: #@ app
spec:
  selector:
    app: #@ app
  ports:
    - protocol: TCP
      port: #@ app_port
      targetPort: #@ app_port
  type: ClusterIP