#@ load("@ytt:data", "data")
#@ app = "redis"
#@ app_port = data.values.REDIS_PORT
#@ image = "bitnami/redis:latest"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ app + "-deployment"
  labels:
    app: #@ app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #@ app
  template:
    metadata:
      labels:
        app: #@ app
    spec:
      containers:
        - name: #@ app
          image: #@ image
          ports:
            - containerPort: #@ app_port
          env:
            - name: REDIS_PORT_NUMBER
              value: #@ "{}".format(app_port)
            - name: REDIS_PASSWORD
              value: #@ data.values.REDIS_PASSWORD
          livenessProbe:
            exec:
              command:
                - redis-cli
                - --no-auth-warning
                - -a
                - test
                - PING
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - redis-cli
                - --no-auth-warning
                - -a
                - test
                - PING
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: #@ app
spec:
  selector:
    app: #@ app
  ports:
    - protocol: TCP
      port: #@ app_port
      targetPort: #@ app_port
  type: ClusterIP