// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ITransactionItem interface {
	IsITransactionItem()
}

type Approver struct {
	ID                *string `json:"id"`
	RuleInstanceID    *string `json:"rule_instance_id"`
	TransactionID     *string `json:"transaction_id"`
	TransactionItemID *string `json:"transaction_item_id"`
	AccountName       *string `json:"account_name"`
	AccountRole       *string `json:"account_role"`
	DeviceID          *string `json:"device_id"`
	DeviceLatlng      *string `json:"device_latlng"`
	ApprovalTime      *string `json:"approval_time"`
	RejectionTime     *string `json:"rejection_time"`
	ExpirationTime    *string `json:"expiration_time"`
}

type Transaction struct {
	ID                 *string            `json:"id"`
	RuleInstanceID     *string            `json:"rule_instance_id"`
	Author             *string            `json:"author"`
	AuthorDeviceID     *float64           `json:"author_device_id"`
	AuthorDeviceLatlng *float64           `json:"author_device_latlng"`
	AuthorRole         *string            `json:"author_role"`
	EquilibriumTime    *string            `json:"equilibrium_time"`
	SumValue           *string            `json:"sum_value"`
	TransactionItems   []*TransactionItem `json:"transaction_items"`
}

type TransactionInput struct {
	ID                 *string  `json:"id"`
	RuleInstanceID     *string  `json:"rule_instance_id"`
	Author             *string  `json:"author"`
	AuthorDeviceID     *float64 `json:"author_device_id"`
	AuthorDeviceLatlng *float64 `json:"author_device_latlng"`
	AuthorRole         *string  `json:"author_role"`
}

type TransactionItem struct {
	ID                     *string     `json:"id"`
	TransactionID          *string     `json:"transaction_id"`
	ItemID                 *string     `json:"item_id"`
	Price                  *string     `json:"price"`
	Quantity               *string     `json:"quantity"`
	DebitorFirst           *bool       `json:"debitor_first"`
	RuleInstanceID         *string     `json:"rule_instance_id"`
	UnitOfMeasurement      *string     `json:"unit_of_measurement"`
	UnitsMeasured          *string     `json:"units_measured"`
	Debitor                *string     `json:"debitor"`
	Creditor               *string     `json:"creditor"`
	DebitorProfileID       *string     `json:"debitor_profile_id"`
	CreditorProfileID      *string     `json:"creditor_profile_id"`
	DebitorApprovalTime    *string     `json:"debitor_approval_time"`
	CreditorApprovalTime   *string     `json:"creditor_approval_time"`
	DebitorExpirationTime  *string     `json:"debitor_expiration_time"`
	CreditorExpirationTime *string     `json:"creditor_expiration_time"`
	DebitorRejectionTime   *string     `json:"debitor_rejection_time"`
	CreditorRejectionTime  *string     `json:"creditor_rejection_time"`
	Approvers              []*Approver `json:"approvers"`
}

func (TransactionItem) IsITransactionItem() {}

type TransactionItemInput struct {
	ID                     *string `json:"id"`
	TransactionID          *string `json:"transaction_id"`
	ItemID                 *string `json:"item_id"`
	Price                  *string `json:"price"`
	Quantity               *string `json:"quantity"`
	DebitorFirst           *bool   `json:"debitor_first"`
	RuleInstanceID         *string `json:"rule_instance_id"`
	UnitOfMeasurement      *string `json:"unit_of_measurement"`
	UnitsMeasured          *string `json:"units_measured"`
	Debitor                *string `json:"debitor"`
	Creditor               *string `json:"creditor"`
	DebitorProfileID       *string `json:"debitor_profile_id"`
	CreditorProfileID      *string `json:"creditor_profile_id"`
	DebitorApprovalTime    *string `json:"debitor_approval_time"`
	CreditorApprovalTime   *string `json:"creditor_approval_time"`
	DebitorExpirationTime  *string `json:"debitor_expiration_time"`
	CreditorExpirationTime *string `json:"creditor_expiration_time"`
	DebitorRejectionTime   *string `json:"debitor_rejection_time"`
	CreditorRejectionTime  *string `json:"creditor_rejection_time"`
}
