name: mxf
services:
  request-approve:
    build:
      context: ../
      dockerfile: ./docker/dev/request-approve.Dockerfile
    ports:
      - "8082:8080"
    environment:
      PGDATABASE: mxfactorial
      PGUSER: test
      PGPASSWORD: test
      PGHOST: postgres
      PGPORT: 5432
      PG_MAX_CONNECTIONS: 20
      PG_IDLE_TIMEOUT: 10000
      PG_CONN_TIMEOUT: 500
      READINESS_CHECK_PATH: /healthz
    depends_on:
      - postgres
