name: mxf
services:
  postgres:
    build:
      context: ../
      dockerfile: ./docker/dev/bitnami-postgres.Dockerfile
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
