name: mxf
services:
  request-by-id:
    build:
      context: ../
      dockerfile: ./docker/dev/request-by-id.Dockerfile
    ports:
      - "10005:10005"
    environment:
      PGDATABASE: mxfactorial
      PGUSER: test
      PGPASSWORD: test
      PGHOST: postgres
      PGPORT: 5432
      PG_MAX_CONNECTIONS: 20
      PG_IDLE_TIMEOUT: 10000
      PG_CONN_TIMEOUT: 500
      READINESS_CHECK_PATH: /healthz
      REQUEST_BY_ID_PORT: 10005
    depends_on:
      - postgres
