name: mxf
services:
  transaction-by-id:
    build:
      context: ../
      dockerfile: ./docker/dev/transaction-by-id.Dockerfile
    ports:
      - "10007:10007"
    environment:
      PGDATABASE: mxfactorial
      PGUSER: test
      PGPASSWORD: test
      PGHOST: postgres
      PGPORT: 5432
      PG_MAX_CONNECTIONS: 20
      PG_IDLE_TIMEOUT: 10000
      PG_CONN_TIMEOUT: 500
      READINESS_CHECK_PATH: /healthz
      TRANSACTION_BY_ID_PORT: 10007
    depends_on:
      - postgres
