name: mxf
services:
  request-create:
    build:
      context: ../
      dockerfile: ./docker/dev/request-create.Dockerfile
    ports:
      - "10002:10002"
    environment:
      PGDATABASE: mxfactorial
      PGUSER: test
      PGPASSWORD: test
      PGHOST: postgres
      PGPORT: 5432
      PG_MAX_CONNECTIONS: 20
      PG_IDLE_TIMEOUT: 10000
      PG_CONN_TIMEOUT: 500
      READINESS_CHECK_PATH: /healthz
      RULE_URL: http://rule:10001
      REQUEST_CREATE_PORT: 10002
    depends_on:
      - postgres
