name: mxf
services:
  rule:
    build:
      context: ../
      dockerfile: ./docker/dev/rule.Dockerfile
    ports:
      - "10001:10001"
    environment:
      PGDATABASE: mxfactorial
      PGUSER: test
      PGPASSWORD: test
      PGHOST: postgres
      PGPORT: 5432
      PG_MAX_CONNECTIONS: 20
      PG_IDLE_TIMEOUT: 10000
      PG_CONN_TIMEOUT: 500
      READINESS_CHECK_PATH: /healthz
      RUST_LOG: info
      RULE_PORT: 10001
    depends_on:
      - postgres
