name: mxf
services:
  postgres:
    build:
      context: ../
      dockerfile: ./docker/bitnami-postgres.Dockerfile
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli --no-auth-warning -a test PING | grep PONG
      interval: 1s
      timeout: 5s
      retries: 5
    environment:
      REDIS_PORT_NUMBER: 6379
      REDIS_PASSWORD: test
  graphql:
    image: graphql:latest
    build:
      context: ../
      dockerfile: ./docker/graphql.Dockerfile
    ports:
      - "10000:10000"
    environment:
      RULE_URL: "http://rule:10001"
      REQUEST_CREATE_URL: "http://request-create:10002"
      REQUEST_APPROVE_URL: "http://request-approve:10003"
      REQUEST_BY_ID_URL: "http://request-by-id:10005"
      REQUESTS_BY_ACCOUNT_URL: "http://requests-by-account:10006"
      TRANSACTIONS_BY_ACCOUNT_URL: "http://transactions-by-account:10008"
      TRANSACTION_BY_ID_URL: "http://transaction-by-id:10007"
      BALANCE_BY_ACCOUNT_URL: "http://balance-by-account:10004"
      READINESS_CHECK_PATH: "/healthz"
      RUST_LOG: info
      GRAPHQL_PORT: 10000
  balance-by-account:
    image: balance-by-account:latest
    build:
      context: ../
      dockerfile: ./docker/balance-by-account.Dockerfile
    ports:
      - "10004:10004"
    environment:
      PGDATABASE: mxfactorial
      PGUSER: test
      PGPASSWORD: test
      PGHOST: postgres
      PGPORT: 5432
      PG_MAX_CONNECTIONS: 20
      PG_IDLE_TIMEOUT: 10000
      PG_CONN_TIMEOUT: 500
      READINESS_CHECK_PATH: /healthz
      BALANCE_BY_ACCOUNT_PORT: 10004
    depends_on:
      - postgres
  request-create:
    image: request-create:latest
    build:
      context: ../
      dockerfile: ./docker/request-create.Dockerfile
    ports:
      - "10002:10002"
    environment:
      PGDATABASE: mxfactorial
      PGUSER: test
      PGPASSWORD: test
      PGHOST: postgres
      PGPORT: 5432
      PG_MAX_CONNECTIONS: 20
      PG_IDLE_TIMEOUT: 10000
      PG_CONN_TIMEOUT: 500
      READINESS_CHECK_PATH: /healthz
      RULE_URL: http://rule:10001
      REQUEST_CREATE_PORT: 10002
    depends_on:
      - postgres
  request-approve:
    image: request-approve:latest
    build:
      context: ../
      dockerfile: ./docker/request-approve.Dockerfile
    ports:
      - "10003:10003"
    environment:
      PGDATABASE: mxfactorial
      PGUSER: test
      PGPASSWORD: test
      PGHOST: postgres
      PGPORT: 5432
      PG_MAX_CONNECTIONS: 20
      PG_IDLE_TIMEOUT: 10000
      PG_CONN_TIMEOUT: 500
      READINESS_CHECK_PATH: /healthz
      REQUEST_APPROVE_PORT: 10003
    depends_on:
      - postgres
  rule:
    image: rule:latest
    build:
      context: ../
      dockerfile: ./docker/rule.Dockerfile
    ports:
      - "10001:10001"
    environment:
      PGDATABASE: mxfactorial
      PGUSER: test
      PGPASSWORD: test
      PGHOST: postgres
      PGPORT: 5432
      PG_MAX_CONNECTIONS: 20
      PG_IDLE_TIMEOUT: 10000
      PG_CONN_TIMEOUT: 500
      READINESS_CHECK_PATH: /healthz
      RUST_LOG: info
      RULE_PORT: 10001
    depends_on:
      - postgres
  request-by-id:
    image: request-by-id:latest
    build:
      context: ../
      dockerfile: ./docker/request-by-id.Dockerfile
    ports:
      - "10005:10005"
    environment:
      PGDATABASE: mxfactorial
      PGUSER: test
      PGPASSWORD: test
      PGHOST: postgres
      PGPORT: 5432
      PG_MAX_CONNECTIONS: 20
      PG_IDLE_TIMEOUT: 10000
      PG_CONN_TIMEOUT: 500
      READINESS_CHECK_PATH: /healthz
      REQUEST_BY_ID_PORT: 10005
    depends_on:
      - postgres
  requests-by-account:
    image: requests-by-account:latest
    build:
      context: ../
      dockerfile: ./docker/requests-by-account.Dockerfile
    ports:
      - "10006:10006"
    environment:
      PGDATABASE: mxfactorial
      PGUSER: test
      PGPASSWORD: test
      PGHOST: postgres
      PGPORT: 5432
      PG_MAX_CONNECTIONS: 20
      PG_IDLE_TIMEOUT: 10000
      PG_CONN_TIMEOUT: 500
      READINESS_CHECK_PATH: /healthz
      RETURN_RECORD_LIMIT: 20
      REQUESTS_BY_ACCOUNT_PORT: 10006
    depends_on:
      - postgres
  transaction-by-id:
    image: transaction-by-id:latest
    build:
      context: ../
      dockerfile: ./docker/transaction-by-id.Dockerfile
    ports:
      - "10007:10007"
    environment:
      PGDATABASE: mxfactorial
      PGUSER: test
      PGPASSWORD: test
      PGHOST: postgres
      PGPORT: 5432
      PG_MAX_CONNECTIONS: 20
      PG_IDLE_TIMEOUT: 10000
      PG_CONN_TIMEOUT: 500
      READINESS_CHECK_PATH: /healthz
      TRANSACTION_BY_ID_PORT: 10007
    depends_on:
      - postgres
  transactions-by-account:
    image: transactions-by-account:latest
    build:
      context: ../
      dockerfile: ./docker/transactions-by-account.Dockerfile
    ports:
      - "10008:10008"
    environment:
      PGDATABASE: mxfactorial
      PGUSER: test
      PGPASSWORD: test
      PGHOST: postgres
      PGPORT: 5432
      PG_MAX_CONNECTIONS: 20
      PG_IDLE_TIMEOUT: 10000
      PG_CONN_TIMEOUT: 500
      READINESS_CHECK_PATH: /healthz
      RETURN_RECORD_LIMIT: 20
      TRANSACTIONS_BY_ACCOUNT_PORT: 10008
    depends_on:
      - postgres
  event:
    image: event:latest
    build:
      context: ../
      dockerfile: ./docker/event.Dockerfile
    environment:
      PGDATABASE: mxfactorial
      PGUSER: test
      PGPASSWORD: test
      PGHOST: postgres
      PGPORT: 5432
      REDIS_DB: 0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: default
      REDIS_PASSWORD: test
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
  measure:
    image: measure:latest
    build:
      context: ../
      dockerfile: ./docker/measure.Dockerfile
    ports:
      - "10010:10010"
    environment:
      PGDATABASE: mxfactorial
      PGUSER: test
      PGPASSWORD: test
      PGHOST: postgres
      PGPORT: 5432
      REDIS_DB: 0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: default
      REDIS_PASSWORD: test
      MEASURE_PORT: 10010
      READINESS_CHECK_PATH: "/healthz"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
  client:
    build:
      context: ../
      dockerfile: ./docker/client.Dockerfile
    ports:
      - "10009:10009"
    environment:
      # WARNING: dupe config from client/.env
      # PUBLIC variable name prefix normally added by
      # make -C client prefix-env-vars but added here manually
      PUBLIC_POOL_ID: localhost
      PUBLIC_CLIENT_ID: localhost
      PUBLIC_GRAPHQL_URI: http://graphql:10000
      PUBLIC_GOOGLE_MAPS_API_KEY: null
      PORT: 10009

