var config = require('../core/config.json');
var gcloud = require('gcloud');
var async = require('async');

var ds = gcloud.datastore({
  projectId: config.GCLOUD_PROJECT
});

//Create new user with kind Account. Key is not specified and generated by datastore.
exports.createUser = function(data, cb){
    
    if(data.account.auth.user_create){
        //Create key for storing entity
        var key = ds.key(['Account',data.account.auth.user_create]);
    }else{
        var key = ds.key(['Account']);
    }
    
    //Insert entity into datastore. Insert returns object if successful.
    ds.save({
        key: key,
        data: data
    }, function(err,result){
        if (err)
            cb(err);
        else
            cb(null,result);
    });
    
};

//Query datastore for all entities of kind Account
exports.getAll = function(cb){
    
    //Build query to find all entities with kind=='Account'
    var q = ds.createQuery('Account');
    
    //Run query and return results
    ds.runQuery(q, function(err,result) {
        if (err)
            cb(err);
        else
            cb(null,result);
    });
}

//Delete single entity using key
exports.delete = function(key,cb){
    //Delete entity with specified key
    ds.delete(key, function(err) {
        if (err) 
            cb(err);
        else
            cb(null);
    });
}

//Delete all entities of kind Account. Returns array of keys of deleted entities
exports.deleteAll = function(cb){
    
    var q = ds.createQuery('Account');
    
    var deleted = [];
    
    ds.runQuery(q, function(err,result) {
        if (err){
            cb(err);
        }else{
            async.each(result,
                //Function to delete each item found
                function(obj,complete){
                    ds.delete(obj.key, function(err) {
                    if (err) {
                        cb(err);
                    }else{
                        deleted.push(obj.key);
                        complete();
                    }});
                },
                //Callback once all items deleted
                function(err){
                    cb(null,deleted);
                }
            );
        }
    });
}