// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/systemaccounting/mxfactorial/pkg/types (interfaces: TrItemListHelper,IScanRow,IScanRows)

// Package mock_types is a generated GoMock package.
package mock_types

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v4"
	decimal "github.com/shopspring/decimal"
)

// MockTrItemListHelper is a mock of TrItemListHelper interface.
type MockTrItemListHelper struct {
	ctrl     *gomock.Controller
	recorder *MockTrItemListHelperMockRecorder
}

// MockTrItemListHelperMockRecorder is the mock recorder for MockTrItemListHelper.
type MockTrItemListHelperMockRecorder struct {
	mock *MockTrItemListHelper
}

// NewMockTrItemListHelper creates a new mock instance.
func NewMockTrItemListHelper(ctrl *gomock.Controller) *MockTrItemListHelper {
	mock := &MockTrItemListHelper{ctrl: ctrl}
	mock.recorder = &MockTrItemListHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrItemListHelper) EXPECT() *MockTrItemListHelperMockRecorder {
	return m.recorder
}

// ListUniqueAccountsFromTrItems mocks base method.
func (m *MockTrItemListHelper) ListUniqueAccountsFromTrItems() []interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUniqueAccountsFromTrItems")
	ret0, _ := ret[0].([]interface{})
	return ret0
}

// ListUniqueAccountsFromTrItems indicates an expected call of ListUniqueAccountsFromTrItems.
func (mr *MockTrItemListHelperMockRecorder) ListUniqueAccountsFromTrItems() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUniqueAccountsFromTrItems", reflect.TypeOf((*MockTrItemListHelper)(nil).ListUniqueAccountsFromTrItems))
}

// ListUniqueDebitorAccountsFromTrItems mocks base method.
func (m *MockTrItemListHelper) ListUniqueDebitorAccountsFromTrItems() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUniqueDebitorAccountsFromTrItems")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ListUniqueDebitorAccountsFromTrItems indicates an expected call of ListUniqueDebitorAccountsFromTrItems.
func (mr *MockTrItemListHelperMockRecorder) ListUniqueDebitorAccountsFromTrItems() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUniqueDebitorAccountsFromTrItems", reflect.TypeOf((*MockTrItemListHelper)(nil).ListUniqueDebitorAccountsFromTrItems))
}

// MapDebitorsToRequiredFunds mocks base method.
func (m *MockTrItemListHelper) MapDebitorsToRequiredFunds() map[string]decimal.Decimal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapDebitorsToRequiredFunds")
	ret0, _ := ret[0].(map[string]decimal.Decimal)
	return ret0
}

// MapDebitorsToRequiredFunds indicates an expected call of MapDebitorsToRequiredFunds.
func (mr *MockTrItemListHelperMockRecorder) MapDebitorsToRequiredFunds() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapDebitorsToRequiredFunds", reflect.TypeOf((*MockTrItemListHelper)(nil).MapDebitorsToRequiredFunds))
}

// MockIScanRow is a mock of IScanRow interface.
type MockIScanRow struct {
	ctrl     *gomock.Controller
	recorder *MockIScanRowMockRecorder
}

// MockIScanRowMockRecorder is the mock recorder for MockIScanRow.
type MockIScanRowMockRecorder struct {
	mock *MockIScanRow
}

// NewMockIScanRow creates a new mock instance.
func NewMockIScanRow(ctrl *gomock.Controller) *MockIScanRow {
	mock := &MockIScanRow{ctrl: ctrl}
	mock.recorder = &MockIScanRowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIScanRow) EXPECT() *MockIScanRowMockRecorder {
	return m.recorder
}

// ScanRow mocks base method.
func (m *MockIScanRow) ScanRow(arg0 pgx.Row) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanRow", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanRow indicates an expected call of ScanRow.
func (mr *MockIScanRowMockRecorder) ScanRow(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanRow", reflect.TypeOf((*MockIScanRow)(nil).ScanRow), arg0)
}

// MockIScanRows is a mock of IScanRows interface.
type MockIScanRows struct {
	ctrl     *gomock.Controller
	recorder *MockIScanRowsMockRecorder
}

// MockIScanRowsMockRecorder is the mock recorder for MockIScanRows.
type MockIScanRowsMockRecorder struct {
	mock *MockIScanRows
}

// NewMockIScanRows creates a new mock instance.
func NewMockIScanRows(ctrl *gomock.Controller) *MockIScanRows {
	mock := &MockIScanRows{ctrl: ctrl}
	mock.recorder = &MockIScanRowsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIScanRows) EXPECT() *MockIScanRowsMockRecorder {
	return m.recorder
}

// ScanRows mocks base method.
func (m *MockIScanRows) ScanRows(arg0 pgx.Rows) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanRows", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanRows indicates an expected call of ScanRows.
func (mr *MockIScanRowsMockRecorder) ScanRows(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanRows", reflect.TypeOf((*MockIScanRows)(nil).ScanRows), arg0)
}
