variable "api_name" {}
variable "env" {}
variable "lambda_invoke_arn" {}
variable "api_version" {}
variable "enable_api_auto_deploy" {}
variable "payload_format_version" {}
variable "enable_api_auth" {}
variable "cognito_endpoint" {}
variable "cognito_client_id" {}
variable "authorization_header_key" {}
