name: dev-rule

on:
  push:
    paths:
    - 'services/rule/**'
    branches-ignore:
    - 'master'

jobs:
  test:
    name: rule
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt
      - uses: taiki-e/install-action@nextest
      - name: linting
        run: |
          cargo fmt -- --check
          cargo clippy -- -Dwarnings
        working-directory: services/rule
      - name: install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: services/rule unit tests
        run: cargo test
        working-directory: services/rule
      - name: services/rule coverage report
        run: |
          make rust-coverage RUST_PKG=rule
          echo "MIN_CODE_COV=$(yq .services.rule.min_code_cov project.yaml)" >> $GITHUB_ENV
      - name: fail services/rule coverage under ${{ env.MIN_CODE_COV }}%
        run: |
          if [[ $(make rust-coverage-percent RUST_PKG=rule) -lt ${{ env.MIN_CODE_COV }} ]]; then
            echo 'coverage dropped below ${{ env.MIN_CODE_COV }}%'
            exit 1
          fi