name: dev-wss-connect

on:
  push:
    paths:
    - 'services/wss-connect/**'
    branches-ignore:
    - 'master'

jobs:
  test:
    name: wss-connect
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: compile
        run: make compile
        working-directory: services/wss-connect
      - name: zip
        run: make zip
        working-directory: services/wss-connect
      - name: deploy to dev
        run: ENV_ID=${{ secrets.DEV_ENV_ID }} make deploy-only ENV=dev
        working-directory: services/wss-connect