name: dev-migrations

on:
  push:
    paths:
    - 'migrations/schema/**'
    - 'migrations/seed/**'
    - 'migrations/testseed/**'
    branches-ignore:
    - 'master'

jobs:
  tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
      - name: install deps
        run: make install
        working-directory: migrations
      - name: run postgres in docker container
        run: make run-ci
        working-directory: migrations
      - name: up migrate from schema, seed and testseed directories
        run: make updocker DB=test
        working-directory: migrations
      # todo: add insert, update and select tests
      - name: stop container and clean up postgres docker data
        run: make clean