name: dev-request-create

on:
  push:
    paths:
    - 'services/request-create/**'
    branches-ignore:
    - 'master'

jobs:
  test:
    name: request-create in dev
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      # - name: measure coverage
      #   run: make test-cover
      #   working-directory: services/request-create
      # - name: unit tests
      #   run: make test-unit
      #   working-directory: services/request-create
      - name: compile
        run: make compile
        working-directory: services/request-create
      - name: zip
        run: make zip
        working-directory: services/request-create
      - name: deploy to dev
        run: make deploy-only ENV=dev
        working-directory: services/request-create
      # - name: integration tests
      #   run: make test-integration ENV=dev
      #   working-directory: services/request-create