name: dev-gopkg-tools

on:
  push:
    paths:
    - 'services/gopkg/tools/**'
    branches-ignore:
    - 'master'

jobs:
  build:
    name: gopkg-tools
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
      - name: unit test
        run: go test -race -covermode=atomic -coverprofile=coverage.out
        working-directory: services/gopkg/tools
      - name: set CODECOV_FLAGS env var
        run: bash scripts/set-codecov-flags.sh --app-or-pkg-name tools --test-type unittest
      - name: report coverage
        uses: codecov/codecov-action@v2
        with:
          flags: ${{ env.CODECOV_FLAGS }}