name: dev-rules-faas

on:
  push:
    paths:
    - 'services/rules-faas/**'
    branches-ignore:
    - 'master'

jobs:
  test:
    name: rules-faas unit and integration tests
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: install prod and dev dependencies
        run: make install
        working-directory: services/rules-faas
      - name: unit tests
        run: make test-unit
        working-directory: services/rules-faas
      - name: deploy to dev
        run: make deploy ENV=dev
        working-directory: services/rules-faas
      - name: build .env file from secrets manager
        run: make get-secrets ENV=dev
        working-directory: services/rules-faas
      - name: integration tests
        run: make test-integration ENV=dev
        working-directory: services/rules-faas