name: dev-balance-by-account

on:
  push:
    paths:
    - 'services/balance-by-account/**'
    branches-ignore:
    - 'master'

jobs:
  test:
    name: balance-by-account in dev
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: compile
        run: make compile
        working-directory: services/balance-by-account
      - name: zip
        run: make zip
        working-directory: services/balance-by-account
      - name: deploy to dev
        run: make deploy-only ENV=dev
        working-directory: services/balance-by-account