name: dev-pkg-lambda

on:
  push:
    paths:
    - 'pkg/aws/lambda/**'
    branches-ignore:
    - 'master'

jobs:
  lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: unit test
        run: make test
        working-directory: pkg/aws/lambda