name: dev-crates

on:
  push:
    paths:
    - 'crates/**'
    branches-ignore:
    - 'master'

jobs:
  test:
    name: crates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt
      - uses: taiki-e/install-action@nextest
      - name: crates lint
        run: |
          cargo fmt -p pg -p types -p httpclient -- --check
          cargo clippy -p pg -p types -p httpclient -- -Dwarnings
      - name: install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: crates unit tests
        run: cargo test -p pg -p types -p httpclient
      - name: crates/types coverage report
        run: |
          make rust-coverage RUST_PKG=types
      - name: crates/pg coverage report
        run: |
          make rust-coverage RUST_PKG=pg
      - name: crates/httpclient coverage report
        run: |
          make rust-coverage RUST_PKG=httpclient