name: dev-react

on:
  push:
    paths:
    - 'react/**'
    branches-ignore:
    - 'master'

jobs:
  test:
    name: react unit and e2e tests in dev
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: make install
        working-directory: react
      - name: unit tests
        run: |
          make get-secrets ENV=dev
          make test-unit
        working-directory: react
      # - name: integration tests
      #   run: |
      #     yarn test:e2e-public
      #     yarn test:e2e-private
      #   working-directory: react
      - name: build for dev
        run: make build ENV=dev
        working-directory: react
      - name: sync build to s3 dev
        run: make sync ENV=dev
        working-directory: react
      - name: empty cache in dev
        run: make empty-cache ENV=dev
        working-directory: react
