name: dev-clone

on:
  push:
    paths:
    - 'schema/clone-faas/**'
    branches-ignore:
    - 'master'
  pull_request:
    paths:
    - 'schema/clone-faas/**'
    branches-ignore:
    - 'master'

jobs:
  build:
    name: clone-faas
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: use node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install yarn
        uses: sergioramos/yarn-actions/install@master
      - name: install aws cli
        uses: chrislennon/action-aws-cli@v1.1
      - name: create zip for deployment
        run: make zip
        working-directory: schema/clone-faas
      - name: deploy
        run: make deploy-only ENV=dev
        working-directory: schema/clone-faas