name: dev-rules-faas

on:
  push:
    paths:
    - 'services/rules-faas/**'
    branches-ignore:
    - 'master'

jobs:
  test:
    name: rules-faas unit and integration tests
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies and execute unit tests
        run: make test-unit ENV=dev
        working-directory: services/rules-faas
      - name: deploy and execute integraton tests
        run: make test-integration ENV=dev
        working-directory: services/rules-faas