name: dev-rules

on:
  push:
    paths:
    - 'services/rules/**'
    branches-ignore:
    - 'master'

jobs:
  test:
    name: rules
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: install prod and dev dependencies
        run: make install
        working-directory: services/rules
      - name: unit tests
        run: make test-unit
        working-directory: services/rules
      - name: deploy to dev
        run: ENV_ID=${{ secrets.DEV_ENV_ID }} make deploy ENV=dev
        working-directory: services/rules
      - name: create .env file
        run: ENV_ID=${{ secrets.DEV_ENV_ID }} make get-secrets ENV=dev
        working-directory: services/rules
      - name: integration tests
        run: make test-integration ENV=dev
        working-directory: services/rules