name: dev-gopkg-sqls

on:
  push:
    paths:
    - 'services/gopkg/sqls/**'
    branches-ignore:
    - 'master'

env:
  ENVIRONMENT: dev

jobs:
  sqls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
      - name: install deps
        run: make install
        working-directory: services/gopkg/sqls
      - name: generate mocks
        run: make mock
        working-directory: services/gopkg/sqls
      - name: unit test
        run: make test
        working-directory: services/gopkg/sqls
      - name: set CODECOV_FLAGS env var
        run: bash scripts/set-codecov-flags.sh --app-or-pkg-name sqls --test-type unittest
      - name: report coverage
        uses: codecov/codecov-action@v2
        with:
          flags: ${{ env.CODECOV_FLAGS }}