name: dev-rules

on:
  push:
    paths:
    - 'services/rules/**'
    branches-ignore:
    - 'master'

jobs:
  test:
    name: rules
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: install prod and dev dependencies
        run: make -C services/rules install
      - name: unit tests
        run: make -C services/rules test-unit
      - name: deploy to dev
        run: ENV_ID=${{ secrets.DEV_ENV_ID }} make -C services/rules deploy ENV=dev
      - name: create .env file
        run: ENV_ID=${{ secrets.DEV_ENV_ID }} make -C services/rules get-secrets ENV=dev
      - name: cloud integration tests
        run: make -C services/rules test-cloud ENV=dev