name: dev-delete-faker-cognito

on:
  push:
    paths:
    - 'infrastructure/terraform/aws/modules/environment/common-bin/cognito/delete-faker-accounts/**'
    branches-ignore:
    - 'master'

jobs:
  build:
    name: update-faas
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: clean directory
        run: make clean
        working-directory: infrastructure/terraform/aws/modules/environment/common-bin/cognito/delete-faker-accounts
      - name: create zip for deployment
        run: make zip
        working-directory: infrastructure/terraform/aws/modules/environment/common-bin/cognito/delete-faker-accounts
      - name: deploy
        run: make deploy-only ENV=dev
        working-directory: infrastructure/terraform/aws/modules/environment/common-bin/cognito/delete-faker-accounts