name: prod-measure-faas

on:
  push:
    paths:
    - 'services/measure-faas/**'
    branches:
    - 'master'

jobs:
  build:
    name: measure-faas
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
      GOPATH: $GITHUB_WORKSPACE/go
    steps:
      - uses: actions/checkout@v1
      - name: use default go
        uses: actions/setup-go@v1
      - name: install aws cli
        uses: chrislennon/action-aws-cli@v1.1
      - name: install dependencies
        run: make install
        working-directory: services/measure-faas
      - name: compile
        run: make compile
        working-directory: services/measure-faas
      - name: zip
        run: make zip
        working-directory: services/measure-faas
      - name: deloy
        run: make deploy-only ENV=dev
        working-directory: services/measure-faas