name: prod-request-create

on:
  push:
    paths:
    - 'services/request-create-faas/**'
    branches:
    - 'master'

jobs:
  deploy:
    name: deploy request-create-faas to prod
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: deploy to prod
        working-directory: services/request-create-faas
        run: make deploy ENV=prod