name: prod-rule

on:
  push:
    paths:
    - 'services/rule/**'
    branches:
    - 'master'

jobs:
  deploy:
    name: deploy rule to prod
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v3
      - name: install cargo cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: deploy
        working-directory: services/rule
        run: ENV_ID=${{ secrets.PROD_ENV_ID }} make deploy ENV=prod