name: prod-rules-faas

on:
  push:
    paths:
    - 'services/rules-faas/**'
    branches:
    - 'master'

jobs:
  deploy:
    name: deploy rules-faas to prod
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: use node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install yarn
        uses: sergioramos/yarn-actions/install@master
      - name: install aws cli
        uses: chrislennon/action-aws-cli@v1.1
      - name: deploy
        working-directory: services/rules-faas
        run: make deploy ENV=prod