name: prod-notification-send-faas

on:
  push:
    paths:
    - 'services/notification/notification-send-faas/**'
    branches:
    - 'master'

jobs:
  deploy:
    name: deploy notification-send-faas to prod
    runs-on: ubuntu-latest
    env:
      CI: true
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@v1
      - name: deploy
        working-directory: services/notification/notification-send-faas
        run: make deploy ENV=prod