name: prod-clone

on:
  push:
    paths:
    - 'schema/clone-faas/**'
    branches:
    - 'master'

jobs:
  deploy:
    name: deploy clone-faas to prod
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: create zip for deployment
        run: make zip
        working-directory: schema/clone-faas
      - name: deploy
        run: make deploy-only ENV=prod
        working-directory: schema/clone-faas