name: prod-react

on:
  push:
    paths:
    - 'react/**'
    branches:
    - 'master'

jobs:
  deploy:
    name: deploy react to prod
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: make install
        working-directory: react
      - name: build for prod
        run: make build ENV=prod
        working-directory: react
      - name: deploy to prod
        run: make deploy ENV=prod
        working-directory: react