name: prod-graphql-faas

on:
  push:
    paths:
    - 'services/graphql-faas/**'
    branches:
    - 'master'

jobs:
  test:
    name: deploy graphql-faas to prod
    runs-on: ubuntu-latest
    env:
      CI: true
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: make install-prod
        working-directory: services/graphql-faas
      - name: deploy to prod
        run: make deploy ENV=prod
        working-directory: services/graphql-faas