name: prod-transactions-by-account

on:
  push:
    paths:
    - 'services/transactions-by-account/**'
    branches:
    - 'master'

jobs:
  build:
    name: transactions-by-account in prod
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: compile
        run: make compile
        working-directory: services/transactions-by-account
      - name: zip
        run: make zip
        working-directory: services/transactions-by-account
      - name: deloy to prod
        run: ENV_ID=${{ secrets.PROD_ENV_ID }} make deploy-only ENV=prod
        working-directory: services/transactions-by-account