name: prod-auto-confirm

on:
  push:
    paths:
    - 'services/auto-confirm/**'
    branches:
    - 'master'
# todo: promote artifacts with s3 cp instead of rebuilding
jobs:
  build:
    name: auto-confirm
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: compile
        run: make compile
        working-directory: services/auto-confirm
      - name: zip
        run: make zip
        working-directory: services/auto-confirm
      - name: deploy to prod
        run: ENV_ID=${{ secrets.PROD_ENV_ID }} make deploy-only ENV=prod
        working-directory: services/auto-confirm