name: prod-graphql-faas

on:
  push:
    paths:
    - 'services/graphql-faas/**'
    branches:
    - 'master'

jobs:
  test:
    name: deploy graphql-faas to prod
    runs-on: ubuntu-latest
    env:
      CI: true
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@v1
      - name: use node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install yarn
        uses: sergioramos/yarn-actions/install@master
      - name: install aws cli
        uses: chrislennon/action-aws-cli@v1.1
      - name: install dependencies
        run: make install
        working-directory: services/graphql-faas
      - name: create archive for deployment
        run: make zip
        working-directory: services/graphql-faas
      - name: deploy to prod for integration testing
        run: make deploy ENV=prod
        working-directory: services/graphql-faas