name: prod-requests-mutation

on:
  push:
    paths:
    - 'services/requests-mutation-faas/**'
    branches:
    - 'master'

jobs:
  deploy:
    name: deploy requests-mutation-faas to prod
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: deploy to prod
        working-directory: services/requests-mutation-faas
        run: make deploy ENV=prod