name: prod-requests-by-account

on:
  push:
    paths:
    - 'services/requests-by-account/**'
    branches:
      - 'master'

jobs:
  build:
    name: requests-by-account in prod
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: compile
        run: make compile
        working-directory: services/requests-by-account
      - name: zip
        run: make zip
        working-directory: services/requests-by-account
      - name: deploy to prod
        run: make deploy-only ENV=prod
        working-directory: services/requests-by-account