name: prod-client

on:
  push:
    paths:
    - 'client/**'
    branches:
    - 'master'

jobs:
  test:
    name: deploy client
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: make install
        working-directory: client
      - name: create .env from secrets manager
        run: ENV_ID=${{ secrets.PROD_ENV_ID }} make get-secrets ENV=prod
        working-directory: client
      - name: build bundle
        run: make build
        working-directory: client
      - name: sync build to s3
        run: ENV_ID=${{ secrets.PROD_ENV_ID }} make sync ENV=prod
        working-directory: client
      - name: empty cache
        run: ENV_ID=${{ secrets.PROD_ENV_ID }} make empty-cache ENV=prod
        working-directory: client
