name: prod-deploy-lambda

on:
  push:
    paths:
    - 'infrastructure/terraform/aws/modules/environment/common-bin/deploy-lambda/**'
    branches:
    - 'master'

jobs:
  deploy:
    name: deploy to prod
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: clean
        run: make clean
        working-directory: infrastructure/terraform/aws/modules/environment/common-bin/deploy-lambda
      - name: create zip for deployment
        run: make zip
        working-directory: infrastructure/terraform/aws/modules/environment/common-bin/deploy-lambda
      - name: deploy
        run: make deploy-only ENV=prod
        working-directory: infrastructure/terraform/aws/modules/environment/common-bin/deploy-lambda