name: go lambda reusable workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      directory:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      app_or_pkg_name:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

jobs:
  test:
    name: test ${{ inputs.app_or_pkg_name }} placeholder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
      - name: unit test
        run: echo "go test -race -covermode=atomic -coverprofile=coverage.out"
        working-directory: ${{ inputs.directory }}
      - name: reduce PENDING_TESTS
        run: bash scripts/remove-pending-test.sh --app-or-pkg-name ${{ inputs.app_or_pkg_name }} --sha ${{ github.sha }} --region ${{ inputs.aws_region }} --env ${{ inputs.environment }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}