name: go lambda reusable workflow

on:
  workflow_call:
    inputs:
      go_version:
        required: true
        type: string
      environment:
        required: true
        type: string
      directory:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      depends_on:
        required: true
        type: string
      app_or_pkg_name:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

jobs:
  test:
    name: test ${{ inputs.app_or_pkg_name }} placeholder
    runs-on: ubuntu-latest
    needs: ${{ inputs.depends_on }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go_version }}
      - name: unit test
        run: echo "go test -race -covermode=atomic -coverprofile=coverage.out"
        working-directory: ${{ inputs.directory }}
      - name: reduce PENDING_TESTS
        run: bash scripts/remove-pending-test.sh --app-or-pkg-name ${{ inputs.app_or_pkg_name }} --sha $GITHUB_SHA --region $AWS_REGION --env ${{ inputs.environment }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}